### ISSUE TITLE
Property 'ecRef' does not exist on type 'Sync'.  TS2339

### ISSUE THREAD

**Issue by creditcoder** [shenghanqin/react-address-picker-cc#7]
![Untitled](https://user-images.githubusercontent.com/53688893/75101489-a55c0680-55b3-11ea-93af-54ca331a570e.png)

**Comment by shenghanqin** [comment]
能否把ecRef的代码贴一下？以及你用的address-picker的版本号？
Can you paste the code of ecRef? And the version number of the address-picker you used?

@creditcoder

**Comment by shenghanqin** [comment]
@creditcoder 你好，如果你15天内不提供完整信息，这个issue将关闭

**Comment by creditcoder** [comment]
I'm also not sure about 'ecRef'.
I can't find in your project source.

**Comment by shenghanqin** [comment]
太久了。就先关了哈。嘻嘻
